id: A6E242840
base_file: fB5FB.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 23:00:50.081775
  last_modified_at: 2022-05-30 23:00:50.081784
